### ISSUE TITLE
Copy Writing Proposal

### ISSUE THREAD

**Issue by Gallantmayor** [jakipatryk/steemconnect-firebase-functions#59]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.
My email: gallantmayor22@gmail.com

**Comment by jakipatryk** [comment]
I don't think they are needed for a project of this size, but you are welcome to start working on them anytime you want, just contact me on Discord (jakipatryk#1263) or on Steem.chat (jakipatryk).
